# Generated by Django 3.2.6 on 2021-08-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='bio',
            new_name='review',
        ),
    ]
